//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMS.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanStatu
    {
        public int applicationID { get; set; }
        public int registrationID { get; set; }
        public string loanStatus { get; set; }
        public string remark { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
