//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMS.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanApplication()
        {
            this.Officers = new HashSet<Officer>();
        }
    
        public int applicationID { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string adharNum { get; set; }
        public string panNum { get; set; }
        public System.DateTime dob { get; set; }
        public decimal monthlyIncome { get; set; }
        public string companyName { get; set; }
        public string photo { get; set; }
        public int registrationID { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual LoanStatu LoanStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Officer> Officers { get; set; }
    }
}
